version: '3.7'
  
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - post_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - my_net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - my_net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DB_SERVER_HOST=postgres
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Moscow
    networks:
      - my_net

  zabbix-agent:
    image: zabbix/zabbix-agent2
    environment:
      - DB_SERVER_HOST=postgres
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - my_net
      

  agent:
    image: portainer/agent:2.19.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - my_net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.19.5
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - my_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


networks:
  my_net:
    driver: bridge

volumes:
  post_data:
  portainer_data:
